# Generated by Django 2.2 on 2019-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_establishment_es_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='es_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
