# Generated by Django 2.2 on 2019-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_auto_20190516_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='es_rating',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
    ]
